#!/usr/bin/env ruby
require 'rubygems'
require 'dbus'
#require '/usr/local/wescontrol/daemon/dbus_fix.rb'
require 'yaml'
require 'drb/drb'

require '/usr/local/wescontrol/daemon/devices/device'
require '/usr/local/wescontrol/daemon/devices/Projector'
require '/usr/local/wescontrol/daemon/devices/VideoSwitcher'

URI = "druby://localhost:8787"

class RControl < DBus::Object
	@room_name
	def initialize(room_name)
		@room_name = room_name
		super("/edu/wesleyan/WesControl/controller")
	end
	
	dbus_interface "edu.wesleyan.WesControl.controller" do
		dbus_method :room_name, "out name:s" do
			[@room_name]
		end
	end
end

config = {}
begin
	config = YAML.load_file(ARGV[0])
	#TODO: actually check whether the config file is valid
rescue
	raise "Please pass a valid configuration file as an argument"
end

@devices = {}

bus          = DBus::SystemBus.instance
service      = bus.request_service("edu.wesleyan.WesControl")
rcontrol     = RControl.new(config['room_name'])
service.export(rcontrol)

config['devices'].each{|device|
	require "/usr/local/wescontrol/daemon/devices/#{device['class']}"
	device = Object.const_get(device['class']).new(device['name'], bus, device)
	@devices[device.name] = device
	service.export(device)
}

FRONT_OBJECT = @devices
$SAFE = 1 # disable eval() and friends
DRb.start_service(URI, FRONT_OBJECT)

while(true) do
	#begin
		main = DBus::Main.new
		main << bus
		main.run
	#rescue
	#	puts "Error: #{$!}"
	#end
end
