# ===========================================================================
# Project:   WescontrolWeb
# Copyright: ©2009 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore

proxy "/rooms", :to => "129.133.92.201:5984"

proxy "/devices", :to => "129.133.92.201:1412"