# ===========================================================================
# Project:   WescontrolWeb
# Copyright: ©2009 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, :"sproutcore/animation"]

proxy "/rooms", :to => "129.133.94.118:5984"

proxy "/devices", :to => "129.133.94.118:1412"