/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VideoSwitcher -p videoswitcher.h:videoswitcher.cpp /home/mwylde/Desktop/videoswitcher_interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "videoswitcher.h"

/*
 * Implementation of interface class VideoSwitcher
 */

VideoSwitcher::VideoSwitcher(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    QTimer *timer = new QTimer(this);
    connect(timer, SIGNAL(timeout()), this, SLOT(checkConnection()));
    timer->start(1000);
}

void VideoSwitcher::checkConnection()
{
    if (this->isValid() != m_connected)
    {
        m_connected = this->isValid();
        emit connected_changed(this->isValid());
    }
}

bool VideoSwitcher::connected() const
{
    return m_connected;
}


VideoSwitcher::~VideoSwitcher()
{
}

