/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VideoSwitcher -p videoswitcher.h:videoswitcher.cpp /home/mwylde/Desktop/videoswitcher_interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef VIDEOSWITCHER_H_1253904966
#define VIDEOSWITCHER_H_1253904966

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface edu.wesleyan.WesControl.videoSwitcher
 */
class VideoSwitcher: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "edu.wesleyan.WesControl.videoSwitcher"; }

public:
    VideoSwitcher(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~VideoSwitcher();
    bool connected() const;

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<uint> input()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("input"), argumentList);
    }

    inline QDBusPendingReply<bool> mute()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("mute"), argumentList);
    }

    inline QDBusPendingReply<QString> set_input(uint number)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(number);
        return asyncCallWithArgumentList(QLatin1String("set_input"), argumentList);
    }

    inline QDBusPendingReply<QString> set_mute(bool on)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(on);
        return asyncCallWithArgumentList(QLatin1String("set_mute"), argumentList);
    }

    inline QDBusPendingReply<QString> set_volume(double volume)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(volume);
        return asyncCallWithArgumentList(QLatin1String("set_volume"), argumentList);
    }

    inline QDBusPendingReply<double> volume()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("volume"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void input_changed(uint input);
    void mute_changed(bool on);
    void volume_changed(double volume);
    void connected_changed(bool connected);

private Q_SLOTS:
    void checkConnection();

private:
    bool m_connected;
};

namespace edu {
  namespace wesleyan {
    namespace WesControl {
      typedef ::VideoSwitcher videoSwitcher;
    }
  }
}
#endif
