fs = require 'fs'
{exec} = require 'child_process'

appFiles = [
	'models/device_model',
	'main'
]

task 'build', 'Build application', ->
	appContents = new Array remaining = appFiles.length
	for file, index in appFiles
		fs.readFile "script/#{file}.coffee", 'utf8', (err, fileContents) ->
			throw err if err
			appContents[index] = fileContents
			process() if --remaining is 0
	process = ->
		fs.writeFile 'app.coffee', appContents.join("\n\n"), 'utf8', (err) ->
			throw err if err
			exec 'coffee --compile app.coffee', (err, stdout, stderr) ->
				throw err if err
				print stdout + stderr
				fs.unlink 'app.coffee', (err) ->
					throw err if err
					puts "Done"
		